version: '2'
 
services:
    nginx:
        # depends_on:
        #     - reverseproxy
        build:
            context: ./
            dockerfile: Dockerfile
        image: nginx:alpine
        restart: always
 
    # apache:
    #     depends_on:
    #         - reverseproxy
    #     image: httpd:alpine
    #     restart: always